name: CI

on: [push]

jobs:
  build:
    name: Build, lint, and test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies with Bun (with cache)
        run: bun install

      - name: Lint
        run: bun lint

      - name: Test
        run: bun test --ci --coverage --max-workers=2

      - name: Build
        run: bun build
